/*
 *   Copyright (C) 2023 YouLanjie
 *   
 *   文件名称：package_list.c
 *   创 建 者：youlanjie
 *   创建日期：2023年08月12日
 *   描    述：定义软件包列表
 *
 */

#include "include.h"

struct Package package_list[] = {
	/* 0 系统 */
	{ 0, "base", "基本系统", -1, 0},
	{ 0, "efibootmgr", "", 1, 0},
	{ 0, "grub", "分区引导", 1, 0},
	{ 0, "linux", "linux系统内核", -1, 0},
	{ 0, "linux-firmware", "Linux的固件文件", -1, 0},
	{ 0, "linux-headers", "Headers and scripts for building modules for the Linux kernel", 1, 0},
	{ 0, "os-prober", "", 1, 0},
	/* 1 开发 */
	{ 1, "adb", "", 0, 0},
	{ 1, "base-devel", "基本构建软件包工具", -1, 0},
	{ 1, "cgdb", "", 0, 0},
	{ 1, "clang", "", 1, 0},
	{ 1, "cmake", "", 0, 0},
	{ 1, "ctags", "", 1, 0},
	{ 1, "gcc", "", 0, 0},
	{ 1, "gdb", "", 1, 0},
	{ 1, "git", "", 0, 0},
	{ 1, "mingw-w64-gcc", "跨平台编译，然并卵", 0, 0},
	/* 2 CLI工具 */
	{ 2, "arch-install-scripts", "", 0, 0},
	{ 2, "archinstall", "", 0, 0},
	{ 2, "archiso", "", 0, 0},
	{ 2, "at", "", 1, 0},
	{ 2, "bat", "高级的文本查看", 0, 0},
	{ 2, "bc", "计算器", 0, 0},
	{ 2, "duf", "硬盘大小(df升级版)", 0, 0},
	{ 2, "emacs", "", 0, 0},
	{ 2, "eva", "计算器", 0, 0},
	{ 2, "figlet", "ASCII字符画", 0, 0},
	{ 2, "fish", "", 1, 0},
	{ 2, "fzf", "模糊查找软件", 1, 0},
	{ 2, "gdu", "硬盘占用分析程序", 0, 0},
	{ 2, "gnupg", "", 1, 0},
	{ 2, "hexedit", "16进制编辑器", 0, 0},
	{ 2, "highlight", "文本查看高亮", 0, 0},
	{ 2, "htop", "高级的top程序", 0, 0},
	{ 2, "indent", "C语言程序格式化工具", 0, 0},
	{ 2, "lolcat", "将输出变为彩色，需要rust", 0, 0},
	{ 2, "man", "", 1, 0},
	{ 2, "man-pages-zh_cn", "man的中文支持", 1, 0},
	{ 2, "mdcat", "终端渲染markdown文件", 0, 0},
	{ 2, "neofetch", "", 0, 0},
	{ 2, "neovim", "编辑器", 1, 0},
	{ 2, "nodejs", "", 1, 0},
	{ 2, "npm", "", 1, 0},
	{ 2, "ntfs-3g", "", 0, 0},
	{ 2, "openssh", "ssh", 1, 0},
	{ 2, "pacman-contrib", "", 0, 0},
	{ 2, "plantuml", "终端绘图程序", 0, 0},
	{ 2, "playerctl", "媒体播放控制", 0, 0},
	{ 2, "powerline", "状态栏插件for vim / i3", 1, 0},
	{ 2, "python-matplotlib", "", 0, 0},
	{ 2, "python-opencv", "", 0, 0},
	{ 2, "python-pip", "", 0, 0},
	{ 2, "python-pygame", "pygame", 0, 0},
	{ 2, "python3", "", 1, 0},
	{ 2, "ranger", "", 0, 0},
	{ 2, "rsync", "", 0, 0},
	{ 2, "sshfs", "", 0, 0},
	{ 2, "syslog-ng", "", 0, 0},
	{ 2, "texlive", "latex的软件包组", 0, 0},
	{ 2, "texlive-lang", "latex多语言支持的包组", 0, 0},
	{ 2, "texlive-langchinese", "latex的中文支持包", 0, 0},
	{ 2, "tmux", "", 1, 0},
	{ 2, "tree", "", 1, 0},
	{ 2, "unrar", "解压RAR文件", 0, 0},
	{ 2, "unzip", "解压ZIP文件", 0, 0},
	{ 2, "vim", "", 0, 0},
	{ 2, "yarn", "", 0, 0},
	{ 2, "yay", "AUR管家", 1, 0},
	{ 2, "zip", "压缩ZIP文件", 0, 0},
	{ 2, "zsh", "shell", 1, 0},
	/* 3 网络工具 */
	{ 3, "aria2", "下载器", 1, 0},
	{ 3, "axel", "下载器", 0, 0},
	{ 3, "curl", "下载器", 1, 0},
	{ 3, "dhcpcd", "", -1, 0},
	{ 3, "firewalld", "防火墙", 1, 0},
	{ 3, "iwd", "连接无线网络用", -1, 0},
	{ 3, "net-tools", "ifconfig", 1, 0},
	{ 3, "nginx", "本地的服务器，但建议手动安装", 0, 0},
	{ 3, "systemd-resolvconf", "", 1, 0},
	{ 3, "v2ray", "代理", 0, 0},
	{ 3, "v2raya", "web界面", 0, 0},
	{ 3, "w3m", "终端的浏览器", 0, 0},
	{ 3, "wget", "下载器", 1, 0},
	{ 3, "zerotier-one", "内网穿透", 0, 0},
	/* 4 图形界面 */
	{ 4, "plasma-meta", "安装kde依赖", 0, 0},
	{ 4, "sddm", "会话管理器", 0, 0},
	{ 4, "xorg", "X服务器", 0, 0},
	{ 4, "xorg-xinit", "", 0, 0},
	/* 5 字体 */
	{ 5, "powerline-fonts", "", 1, 0},
	{ 5, "powerline-fonts", "", 1, 0},
	{ 5, "ttf-fira-code", "", 1, 0},
	{ 5, "ttf-liberation", "", 1, 0},
	{ 5, "ttf-nerd-fonts-symbols", "", 1, 0},
	{ 5, "wqy-zenhei", "中文字体", 1, 0},
	/* 6 GUI工具 */
	{ 6, "alacritty", "第三方终端", 0, 0},
	{ 6, "ark", "压缩包查看", 0, 0},
	{ 6, "conky", "悬浮状态指示器", 0, 0},
	{ 6, "dolphin", "kde文件管理器", 0, 0},
	{ 6, "dunst", "通知程序", 0, 0},
	{ 6, "fcitx5-chinese-addons", "for中文支持", 0, 0},
	{ 6, "fcitx5-im", "包组，fcitx5输入法", 0, 0},
	{ 6, "filelight", "文件占用指示程序", 0, 0},
	{ 6, "flatpak", "flatpak程序支持", 0, 0},
	{ 6, "gnuplot", "", 0, 0},
	{ 6, "gparted", "分区工具", 0, 0},
	{ 6, "grub-customizer", "GRUB菜单图形编辑程序", 0, 0},
	{ 6, "kdeconnect", "链接你的手机", 0, 0},
	{ 6, "konsole", "kde终端", 0, 0},
	{ 6, "kvantum", "kde样式", 0, 0},
	{ 6, "latte-dock", "状态栏", 0, 0},
	{ 6, "qt5ct", "非DE的样式控制程序", 0, 0},
	{ 6, "rofi", "程序菜单", 0, 0},
	{ 6, "screenkey", "", 0, 0},
	{ 6, "slop", "", 0, 0},
	{ 6, "spectacle", "截图软件", 0, 0},
	{ 6, "tigervnc", "VNC远程桌面", 0, 0},
	{ 6, "utools", "", 0, 0},
	{ 6, "virtualbox", "虚拟机", 0, 0},
	{ 6, "wine", "运行Windows程序", 0, 0},
	{ 6, "xcompmgr", "窗口透明", 0, 0},
	{ 6, "xdotool", "终端控制键鼠", 0, 0},
	/* 7 多媒体 */
	{ 7, "alsa-utils", "(*CLI)音频管理", 1, 0},
	{ 7, "blender", "3D建模", 0, 0},
	{ 7, "cmus", "(*CLI)音乐播放器", 1, 0},
	{ 7, "ffmpeg", "(*CLI)媒体处理", 1, 0},
	{ 7, "gimp", "图片编辑", 0, 0},
	{ 7, "gwenview", "图片查看软件", 0, 0},
	{ 7, "imagemagick", "", 0, 0},
	{ 7, "inkscape", "svg图片编辑", 0, 0},
	{ 7, "mpv", "媒体播放器", 0, 0},
	{ 7, "musescore", "谱子播放器", 0, 0},
	{ 7, "obs-studio", "", 0, 0},
	{ 7, "okular", "文档查看", 0, 0},
	{ 7, "shotcut", "视频剪辑", 0, 0},
	{ 7, "vlc", "", 0, 0},
	/* 8 Java */
	{ 8, "jdk8-openjdk", "", 0, 0},
	{ 8, "jdk11-openjdk", "", 0, 0},
	{ 8, "jdk17-openjdk", "", 0, 0},
	{ 8, "java17-openjfx", "", 0, 0},
	/* 9 游戏 */
	{ 9, "cataclysm-dda", "类nethack的rougerlike游戏，有官中", 0, 0},
	{ 9, "flightgear", "飞行模拟器", 0, 0},
	{ 9, "flightgear-data", "飞行模拟器数据", 0, 0},
	{ 9, "hmcl", "'Hello Minecraft! Launcher' MC启动器", 1, 0},
	{ 9, "nethack", "", 0, 0},
	{ 9, "powder-toy", "沙子游戏", 0, 0},
	{ 9, "steam", "", 0, 0},
	{ 9, "unciv", "高仿文明5", 0, 0},
	/* 10 AUR */
	{10, "fbterm", "tty显示中文", 1, 0},
	{10, "feh", "非DE图形界面壁纸", 0, 0},
	{10, "picom-animations-git", "AUR上已经无了，但是本地有备份", 0, 0},
	{10, "transset-df", "手动调节某个窗口的透明度", 0, 0},
	{10, "netease-cloud-music", "网易云音乐", 0, 0},
	{10, "microsoft-edge-stable-bin", "edge浏览器", 1, 0},
	{10, "siji-git", "字体显示", 1, 0},
	{10, "ttf-unifont", "字体", 1, 0},
	{10, "linuxqq", "linux QQ，使用electron", 0, 0},
	{10, "xmind", "思维导图软件", 0, 0},
	{10, "wps-office-cn", "wps", 0, 0},
	{10, "wps-office-mui-zh-cn", "wps", 0, 0},
	{10, "gameconqueror", "游戏内存修改器", 0, 0},
	{10, "cmcl", "mc启动器", 1, 0},
	{10, "visual-studio-code-bin", "VScide", 0, 0},
	{10, "2048.c", "", 0, 0},
	{10, "bsd-games2", "atc", 0, 0},
	{10, "sakura-frp", "内网穿透", 0, 0},
	{10, "ttf-ms-fonts", "", 0, 0},
	{10, "sunloginclient", "向日葵远程控制", 0, 0},
	{10, "baidunetdisk-bin", "百度网盘", 0, 0},
	{10, "pcurses", "用C++写成使用ncurese的alpm前端", 0, 0},
	{10, "fsearch", "快速搜索（然并卵）", 0, 0},
	{10, "bilibili-bin", "", 0, 0},
	/* END */
	{99, NULL, NULL, 0, 0},
};

